version: '3.8'

services:
  # Redis for Session Caching (Optional Development)
  redis:
    image: redis:7-alpine
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=development-password
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - meta-agent-network
    restart: unless-stopped

  # Redis Commander (Optional Redis GUI)
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
      - REDIS_PASSWORD=development-password
    ports:
      - "8081:8081"
    depends_on:
      - redis
    networks:
      - meta-agent-network
    profiles:
      - tools

volumes:
  redis_data:
    driver: local

networks:
  meta-agent-network:
    driver: bridge

# Usage Examples:
#
# Start Redis only (recommended):
#   docker-compose up redis
#
# Start Redis with GUI:
#   docker-compose --profile tools up
#
# Stop and clean:
#   docker-compose down -v
#
# Check Redis status:
#   docker-compose exec redis redis-cli ping
#
# Connect to Redis CLI:
#   docker-compose exec redis redis-cli
#
# Environment Variables for App:
#   UPSTASH_REDIS_REST_URL=http://localhost:6379
#   REDIS_PASSWORD=development-password 